# Slider component
com.vaadin.experimental.sliderComponent=true
# Enable theme component style injection
com.vaadin.experimental.themeComponentStyles=true
# Tailwind CSS framework
com.vaadin.experimental.tailwindCss=true
# Master Detail Layout component
com.vaadin.experimental.masterDetailLayoutComponent=true
# HorizontalLayout and VerticalLayout improvements
com.vaadin.experimental.layoutComponentImprovements=true
